version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    # ports:
    #   - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

# image: renegade768/node-app за image будет браться мой образ с докерхаба, но мы так же можем и локально забилдить с --build

  node-app:
    build: .
    image: renegade768/node-app
    environment:
      - PORT=3000
    # означает, что node-app начнет развертку после mongo контейнера развертывания
    # но не факт, что запустится позже нужно учитывать
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sanjeev
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db
  
  redis:
    image: redis

volumes:
  mongo-db: